#!/usr/bin/env bash
set -euo pipefail
cd "$(dirname "$0")/.."
mkdir -p config/custom_components
ln -sfn "${PWD}/custom_components/octopus_energy_de" "${PWD}/config/custom_components/octopus_energy_de"
exec hass --config "${PWD}/config" --debug
