set_device_preferences:
  name: Set device preferences
  description: Set the target state of charge and target time for a SmartFlex device.
  fields:
    device_id:
      required: true
      selector:
        text:
    target_percentage:
      required: true
      selector:
        number:
          min: 20
          max: 100
          step: 5
    target_time:
      required: true
      selector:
        time: